/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AppController_seed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_root"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/animals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnimalsController_findAll"];
        put?: never;
        post: operations["AnimalsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/animals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AnimalsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["AnimalsController_remove"];
        options?: never;
        head?: never;
        patch: operations["AnimalsController_update"];
        trace?: never;
    };
    "/milk-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MilkRecordsController_findAll"];
        put?: never;
        post: operations["MilkRecordsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/milk-records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MilkRecordsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["MilkRecordsController_remove"];
        options?: never;
        head?: never;
        patch: operations["MilkRecordsController_update"];
        trace?: never;
    };
    "/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkersController_findAll"];
        put?: never;
        post: operations["WorkersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkersController_findOne"];
        put?: never;
        post?: never;
        delete: operations["WorkersController_remove"];
        options?: never;
        head?: never;
        patch: operations["WorkersController_update"];
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TasksController_findAll"];
        put?: never;
        post: operations["TasksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TasksController_findOne"];
        put?: never;
        post?: never;
        delete: operations["TasksController_remove"];
        options?: never;
        head?: never;
        patch: operations["TasksController_update"];
        trace?: never;
    };
    "/feeding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FeedingController_findAll"];
        put?: never;
        post: operations["FeedingController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeding/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FeedingController_findOne"];
        put?: never;
        post?: never;
        delete: operations["FeedingController_remove"];
        options?: never;
        head?: never;
        patch: operations["FeedingController_update"];
        trace?: never;
    };
    "/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DeliveriesController_findAll"];
        put?: never;
        post: operations["DeliveriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deliveries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DeliveriesController_findOne"];
        put?: never;
        post?: never;
        delete: operations["DeliveriesController_remove"];
        options?: never;
        head?: never;
        patch: operations["DeliveriesController_update"];
        trace?: never;
    };
    "/vet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["VetController_findAll"];
        put?: never;
        post: operations["VetController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vet/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["VetController_findOne"];
        put?: never;
        post?: never;
        delete: operations["VetController_remove"];
        options?: never;
        head?: never;
        patch: operations["VetController_update"];
        trace?: never;
    };
    "/farm-development/phases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FarmDevelopmentController_getPhases"];
        put?: never;
        post: operations["FarmDevelopmentController_createPhase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farm-development/phases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FarmDevelopmentController_getPhase"];
        put?: never;
        post?: never;
        delete: operations["FarmDevelopmentController_deletePhase"];
        options?: never;
        head?: never;
        patch: operations["FarmDevelopmentController_updatePhase"];
        trace?: never;
    };
    "/farm-development/phases/{phaseId}/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FarmDevelopmentController_getMilestones"];
        put?: never;
        post: operations["FarmDevelopmentController_createMilestone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farm-development/milestones/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FarmDevelopmentController_getMilestone"];
        put?: never;
        post?: never;
        delete: operations["FarmDevelopmentController_deleteMilestone"];
        options?: never;
        head?: never;
        patch: operations["FarmDevelopmentController_updateMilestone"];
        trace?: never;
    };
    "/farm-development/milestones/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["FarmDevelopmentController_completeMilestone"];
        trace?: never;
    };
    "/farm-development/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FarmDevelopmentController_getProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_findAll"];
        put?: never;
        post: operations["PaymentsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/income": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_findIncome"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_findExpenses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["PaymentsController_remove"];
        options?: never;
        head?: never;
        patch: operations["PaymentsController_update"];
        trace?: never;
    };
    "/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletController_getWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletController_getWalletWithTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example farmer@example.com */
            email: string;
            /** @example secret123 */
            password: string;
            /** @example Shivam */
            name: string;
            /** @example My Dairy Farm */
            farmName?: string;
        };
        AuthUserDto: {
            id: string;
            email: string;
            name: string;
            role: string;
            farmId?: string | null;
        };
        AuthResponseDto: {
            accessToken: string;
            user: components["schemas"]["AuthUserDto"];
        };
        LoginDto: {
            /** @example farmer@example.com */
            email: string;
            /** @example secret123 */
            password: string;
        };
        CreateAnimalDto: {
            /** @example A-001 */
            tagNumber: string;
            /** @example Gauri */
            name?: string;
            /** @example Holstein */
            breed: string;
            /** @example 2025-01-01 */
            dateOfBirth: string;
            /** @example 09:30 */
            timeOfBirth?: string;
            /**
             * @example FEMALE
             * @enum {string}
             */
            gender: "MALE" | "FEMALE";
            /**
             * @example COW
             * @enum {string}
             */
            type: "COW" | "BUFFALO";
            /**
             * @example ADULT
             * @enum {string}
             */
            lifeStage: "CALF" | "HEIFER" | "ADULT";
            /**
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "PREGNANT" | "SICK" | "SOLD" | "DECEASED";
            /**
             * @description How the animal was acquired (born, purchased, etc).
             * @example BORN
             * @enum {string}
             */
            acquisitionType: "BORN" | "PURCHASED";
            /** @example farm_123 */
            farmId?: string;
            /**
             * @description Required when acquisitionType is PURCHASED
             * @example 2025-02-15
             */
            purchaseDate?: string;
            /** @example 45000 */
            purchasePrice?: number;
            /** @example Ramesh Dairy */
            purchaseFromName?: string;
            /** @example 9999999999 */
            purchaseFromMobile?: string;
            /** @example seller@example.com */
            purchaseFromEmail?: string;
            /** @example 350 */
            currentWeight?: number;
            /** @example Healthy and vaccinated */
            notes?: string;
        };
        AnimalDto: {
            id: string;
            tagNumber: string;
            name?: string;
            breed: string;
            /** Format: date-time */
            dateOfBirth: string;
            /** Format: date-time */
            timeOfBirth?: string;
            /** @enum {string} */
            gender: "MALE" | "FEMALE";
            /** @enum {string} */
            type: "COW" | "BUFFALO";
            /** @enum {string} */
            lifeStage: "CALF" | "HEIFER" | "ADULT";
            /** @enum {string} */
            status: "ACTIVE" | "PREGNANT" | "SICK" | "SOLD" | "DECEASED";
            /** @enum {string} */
            acquisitionType: "BORN" | "PURCHASED";
            farmId: string;
            /** Format: date-time */
            purchaseDate?: string;
            purchasePrice?: number;
            purchaseFromName?: string;
            purchaseFromMobile?: string;
            purchaseFromEmail?: string;
            currentWeight?: number;
            notes?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateMilkRecordDto: {
            /** @example animal_123 */
            animalId: string;
            /** @example farm_123 */
            farmId: string;
            /** @example 2026-03-10 */
            date: string;
            /** @enum {string} */
            session: "MORNING" | "EVENING";
            /** @example 8.5 */
            quantity: number;
            /** @example 4.2 */
            fatContent?: number;
            /** @enum {string} */
            quality?: "EXCELLENT" | "GOOD" | "AVERAGE" | "POOR";
            /** @example Good yield today */
            notes?: string;
        };
        MilkRecordDto: {
            id: string;
            farmId: string;
            animalId: string;
            /** Format: date-time */
            date: string;
            /** @enum {string} */
            session: "MORNING" | "EVENING";
            quantity: number;
            fatContent?: number;
            /** @enum {string} */
            quality?: "EXCELLENT" | "GOOD" | "AVERAGE" | "POOR";
            notes?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateWorkerDto: {
            /** @example farm_123 */
            farmId: string;
            /** @example Ravi Kumar */
            name: string;
            /** @example 9999999999 */
            contactNumber: string;
            /** @example ravi@example.com */
            email?: string;
            /** @example Village Road, District */
            address?: string;
            /** @enum {string} */
            role: "MANAGER" | "SUPERVISOR" | "MILKER" | "FEEDER" | "CLEANER" | "DRIVER" | "VETERINARIAN" | "OTHER";
            /** @enum {string} */
            shift: "MORNING" | "EVENING" | "NIGHT" | "DAY" | "FULL_TIME";
            /** @example 15000 */
            salary: number;
            /** @example 2026-01-15 */
            joinDate: string;
            /** @enum {string} */
            status: "ACTIVE" | "ON_LEAVE" | "RESIGNED" | "TERMINATED";
            /** @example Good with cattle handling */
            notes?: string;
        };
        WorkerDto: {
            id: string;
            farmId: string;
            name: string;
            contactNumber: string;
            email?: string;
            address?: string;
            /** @enum {string} */
            role: "MANAGER" | "SUPERVISOR" | "MILKER" | "FEEDER" | "CLEANER" | "DRIVER" | "VETERINARIAN" | "OTHER";
            /** @enum {string} */
            shift: "MORNING" | "EVENING" | "NIGHT" | "DAY" | "FULL_TIME";
            salary: number;
            /** Format: date-time */
            joinDate: string;
            /** @enum {string} */
            status: "ACTIVE" | "ON_LEAVE" | "RESIGNED" | "TERMINATED";
            notes?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateWorkerDto: {
            /** @example farm_123 */
            farmId?: string;
            /** @example Ravi Kumar */
            name?: string;
            /** @example 9999999999 */
            contactNumber?: string;
            /** @example ravi@example.com */
            email?: string;
            /** @example Village Road, District */
            address?: string;
            /** @enum {string} */
            role?: "MANAGER" | "SUPERVISOR" | "MILKER" | "FEEDER" | "CLEANER" | "DRIVER" | "VETERINARIAN" | "OTHER";
            /** @enum {string} */
            shift?: "MORNING" | "EVENING" | "NIGHT" | "DAY" | "FULL_TIME";
            /** @example 15000 */
            salary?: number;
            /** @example 2026-01-15 */
            joinDate?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "ON_LEAVE" | "RESIGNED" | "TERMINATED";
            /** @example Good with cattle handling */
            notes?: string;
        };
        CreateTaskDto: {
            /** @example farm_123 */
            farmId: string;
            /** @example Clean shed */
            title: string;
            /** @example Clean and disinfect the main shed */
            description?: string;
            /** @example worker_123 */
            assignedToId?: string;
            /** @example 2026-03-12 */
            dueDate: string;
            /** @enum {string} */
            priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** @enum {string} */
            status: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
            /** @example Use the new disinfectant */
            notes?: string;
            /** @example user_123 */
            createdById: string;
        };
        TaskDto: {
            id: string;
            farmId: string;
            title: string;
            description?: string;
            assignedToId?: string;
            /** Format: date-time */
            dueDate: string;
            /** @enum {string} */
            priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** @enum {string} */
            status: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
            notes?: string;
            createdById: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateTaskDto: {
            /** @example farm_123 */
            farmId?: string;
            /** @example Clean shed */
            title?: string;
            /** @example Clean and disinfect the main shed */
            description?: string;
            /** @example worker_123 */
            assignedToId?: string;
            /** @example 2026-03-12 */
            dueDate?: string;
            /** @enum {string} */
            priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** @enum {string} */
            status?: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED";
            /** @example Use the new disinfectant */
            notes?: string;
            /** @example user_123 */
            createdById?: string;
        };
        CreateFeedingLogDto: {
            /** @example farm_123 */
            farmId: string;
            /** @example animal_123 */
            animalId: string;
            /** @example 2026-03-10 */
            date: string;
            /** @enum {string} */
            feedingTime: "MORNING" | "AFTERNOON" | "EVENING";
            /** @enum {string} */
            feedType: "HAY" | "SILAGE" | "CONCENTRATE" | "GRAINS" | "MINERAL_SUPPLEMENTS" | "FRESH_GRASS";
            /** @example 5 */
            quantity: number;
            /** @example 200 */
            cost?: number;
            /** @example Added supplements */
            notes?: string;
            /** @example user_123 */
            recordedById: string;
        };
        FeedingLogDto: {
            id: string;
            farmId: string;
            animalId: string;
            /** Format: date-time */
            date: string;
            /** @enum {string} */
            feedingTime: "MORNING" | "AFTERNOON" | "EVENING";
            /** @enum {string} */
            feedType: "HAY" | "SILAGE" | "CONCENTRATE" | "GRAINS" | "MINERAL_SUPPLEMENTS" | "FRESH_GRASS";
            quantity: number;
            cost?: number;
            notes?: string;
            recordedById: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateFeedingLogDto: {
            /** @example farm_123 */
            farmId?: string;
            /** @example animal_123 */
            animalId?: string;
            /** @example 2026-03-10 */
            date?: string;
            /** @enum {string} */
            feedingTime?: "MORNING" | "AFTERNOON" | "EVENING";
            /** @enum {string} */
            feedType?: "HAY" | "SILAGE" | "CONCENTRATE" | "GRAINS" | "MINERAL_SUPPLEMENTS" | "FRESH_GRASS";
            /** @example 5 */
            quantity?: number;
            /** @example 200 */
            cost?: number;
            /** @example Added supplements */
            notes?: string;
            /** @example user_123 */
            recordedById?: string;
        };
        CreateDeliveryDto: {
            /** @example farm_123 */
            farmId: string;
            /** @example 2026-03-10 */
            deliveryDate: string;
            /** @example Local Vendor */
            buyerName: string;
            /** @example 9999999999 */
            buyerPhone?: string;
            /** @example 50 */
            quantity: number;
            /** @example 45 */
            pricePerLiter: number;
            /** @example 2250 */
            totalAmount: number;
            /** @enum {string} */
            deliveryStatus: "PENDING" | "DELIVERED" | "CANCELLED";
            /** @enum {string} */
            paymentStatus: "PENDING" | "PAID" | "PARTIAL" | "OVERDUE";
            /** @example Market road address */
            address?: string;
            /** @example Delivered by worker A */
            notes?: string;
            /** @example user_123 */
            createdById: string;
        };
        DeliveryDto: {
            id: string;
            farmId: string;
            /** Format: date-time */
            deliveryDate: string;
            buyerName: string;
            buyerPhone?: string;
            quantity: number;
            pricePerLiter: number;
            totalAmount: number;
            /** @enum {string} */
            deliveryStatus: "PENDING" | "DELIVERED" | "CANCELLED";
            /** @enum {string} */
            paymentStatus: "PENDING" | "PAID" | "PARTIAL" | "OVERDUE";
            address?: string;
            notes?: string;
            createdById: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateDeliveryDto: {
            /** @example farm_123 */
            farmId?: string;
            /** @example 2026-03-10 */
            deliveryDate?: string;
            /** @example Local Vendor */
            buyerName?: string;
            /** @example 9999999999 */
            buyerPhone?: string;
            /** @example 50 */
            quantity?: number;
            /** @example 45 */
            pricePerLiter?: number;
            /** @example 2250 */
            totalAmount?: number;
            /** @enum {string} */
            deliveryStatus?: "PENDING" | "DELIVERED" | "CANCELLED";
            /** @enum {string} */
            paymentStatus?: "PENDING" | "PAID" | "PARTIAL" | "OVERDUE";
            /** @example Market road address */
            address?: string;
            /** @example Delivered by worker A */
            notes?: string;
            /** @example user_123 */
            createdById?: string;
        };
        CreateVetVisitDto: {
            /** @example animal_123 */
            animalId: string;
            /** @example 2026-03-10 */
            visitDate: string;
            /** @enum {string} */
            visitType?: "ROUTINE" | "EMERGENCY" | "FOLLOWUP" | "VACCINATION" | "CHECKUP";
            /** @example Routine checkup */
            visitReason: string;
            /** @enum {string} */
            treatmentType?: "VACCINATION" | "MEDICATION" | "SURGERY" | "CHECKUP" | "DEWORMING" | "OTHER";
            /** @example Mild fever */
            diagnosis?: string;
            /** @example Administered medication */
            treatment?: string;
            /** @example Paracetamol 2 days */
            prescription?: string;
            /** @example Dr. Sharma */
            veterinarian: string;
            /** @example 800 */
            cost: number;
            /** @enum {string} */
            visitStatus: "SCHEDULED" | "COMPLETED" | "CANCELLED";
            /** @example 2026-03-24 */
            nextVisitDate?: string;
            /** @example Follow-up required */
            notes?: string;
        };
        VetVisitDto: {
            id: string;
            animalId: string;
            /** Format: date-time */
            visitDate: string;
            /** @enum {string} */
            visitType?: "ROUTINE" | "EMERGENCY" | "FOLLOWUP" | "VACCINATION" | "CHECKUP";
            visitReason: string;
            /** @enum {string} */
            treatmentType?: "VACCINATION" | "MEDICATION" | "SURGERY" | "CHECKUP" | "DEWORMING" | "OTHER";
            diagnosis?: string;
            treatment?: string;
            prescription?: string;
            veterinarian: string;
            cost: number;
            /** @enum {string} */
            visitStatus: "SCHEDULED" | "COMPLETED" | "CANCELLED";
            /** Format: date-time */
            nextVisitDate?: string;
            notes?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdateVetVisitDto: {
            /** @example animal_123 */
            animalId?: string;
            /** @example 2026-03-10 */
            visitDate?: string;
            /** @enum {string} */
            visitType?: "ROUTINE" | "EMERGENCY" | "FOLLOWUP" | "VACCINATION" | "CHECKUP";
            /** @example Routine checkup */
            visitReason?: string;
            /** @enum {string} */
            treatmentType?: "VACCINATION" | "MEDICATION" | "SURGERY" | "CHECKUP" | "DEWORMING" | "OTHER";
            /** @example Mild fever */
            diagnosis?: string;
            /** @example Administered medication */
            treatment?: string;
            /** @example Paracetamol 2 days */
            prescription?: string;
            /** @example Dr. Sharma */
            veterinarian?: string;
            /** @example 800 */
            cost?: number;
            /** @enum {string} */
            visitStatus?: "SCHEDULED" | "COMPLETED" | "CANCELLED";
            /** @example 2026-03-24 */
            nextVisitDate?: string;
            /** @example Follow-up required */
            notes?: string;
        };
        FarmDevelopmentPhaseDto: {
            id: string;
            farmId: string;
            name: string;
            description?: string;
            order?: number;
            /** @enum {string} */
            status: "PLANNING" | "LAND_ACQUISITION" | "INFRASTRUCTURE" | "EQUIPMENT_SETUP" | "ANIMAL_ACQUISITION" | "OPERATIONAL";
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
            /** Format: date-time */
            targetDate?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreatePhaseDto: {
            /** @example farm_123 */
            farmId: string;
            /** @example Shed Construction */
            phaseName: string;
            /** @example Build a new cattle shed with proper ventilation */
            description?: string;
            /** @example 1 */
            phaseOrder?: number;
            /**
             * @example NOT_STARTED
             * @enum {string}
             */
            status?: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED" | "ON_HOLD" | "CANCELLED";
            /** @example 0 */
            progress?: number;
            /** @example 250000 */
            budget?: number;
            /** @example 2026-03-01 */
            startDate?: string;
            /** @example 2026-05-01 */
            targetDate?: string;
            /** @example Contractor shortlisted */
            notes?: string;
        };
        UpdatePhaseDto: {
            /** @example Shed Construction */
            phaseName?: string;
            /** @example Updated description */
            description?: string;
            /** @example 2 */
            phaseOrder?: number;
            /**
             * @example IN_PROGRESS
             * @enum {string}
             */
            status?: "NOT_STARTED" | "IN_PROGRESS" | "COMPLETED" | "ON_HOLD" | "CANCELLED";
            /** @example 25 */
            progress?: number;
            /** @example 300000 */
            budget?: number;
            /** @example 50000 */
            actualCost?: number;
            /** @example 2026-03-01 */
            startDate?: string;
            /** @example 2026-05-01 */
            targetDate?: string;
            /** @example 2026-04-15 */
            completedDate?: string;
            /** @example Progress update notes */
            notes?: string;
        };
        FarmDevelopmentMilestoneDto: {
            id: string;
            farmId: string;
            phaseId: string;
            title: string;
            description?: string;
            order?: number;
            /** @enum {string} */
            status: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "BLOCKED";
            /** Format: date-time */
            dueDate?: string;
            /** Format: date-time */
            completedAt?: string;
            costEstimated?: number;
            costActual?: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateMilestoneDto: {
            /** @example Lay foundation */
            title: string;
            /** @example Complete the shed foundation work */
            description?: string;
            /** @example 1 */
            milestoneOrder?: number;
            /**
             * @example PENDING
             * @enum {string}
             */
            status?: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "BLOCKED";
            /** @example 2026-03-20 */
            dueDate?: string;
            /** @example worker_123 */
            assignedToId?: string;
            /** @example Call vendor for cement delivery */
            notes?: string;
        };
        UpdateMilestoneDto: {
            /** @example Lay foundation */
            title?: string;
            /** @example Milestone details updated */
            description?: string;
            /** @example 2 */
            milestoneOrder?: number;
            /**
             * @example COMPLETED
             * @enum {string}
             */
            status?: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "BLOCKED";
            /** @example 2026-03-20 */
            dueDate?: string;
            /** @example 2026-03-18 */
            completedDate?: string;
            /** @example worker_123 */
            assignedToId?: string;
            /** @example Notes for the milestone */
            notes?: string;
        };
        CreatePaymentDto: {
            /**
             * @example INCOME
             * @enum {string}
             */
            type: "INCOME" | "EXPENSE";
            /**
             * @example MILK_SALES
             * @enum {string}
             */
            category: "MILK_SALES" | "ANIMAL_SALES" | "FEED" | "MEDICINE" | "EQUIPMENT" | "LABOR" | "UTILITIES" | "MAINTENANCE" | "VETERINARY" | "TRANSPORT" | "INVESTMENT" | "OTHER_INCOME" | "OTHER_EXPENSE";
            /** @example 1200 */
            amount: number;
            /** @example Milk sale to local vendor */
            description: string;
            /** @example 2026-03-10 */
            date: string;
            /** @example 2026-03-10 */
            transactionDate: string;
            /**
             * @example CASH
             * @enum {string}
             */
            paymentMethod: "CASH" | "CARD" | "UPI" | "BANK_TRANSFER" | "CHEQUE";
            /** @example farm_123 */
            farmId: string;
            /** @example expense_123 */
            referenceId?: string;
            /**
             * @example OTHER
             * @enum {string}
             */
            referenceType?: "EXPENSE" | "DELIVERY" | "VET_VISIT" | "FEEDING_LOG" | "OTHER";
            /** @example Paid in cash at office */
            notes?: string;
        };
        PaymentDto: {
            id: string;
            farmId: string;
            /** @enum {string} */
            type: "INCOME" | "EXPENSE";
            /** @enum {string} */
            method: "CASH" | "CARD" | "UPI" | "BANK_TRANSFER" | "CHEQUE";
            /** @enum {string} */
            status: "PENDING" | "PAID" | "PARTIAL" | "OVERDUE";
            amount: number;
            description?: string;
            /** Format: date-time */
            date?: string;
            reference?: string;
            payerName?: string;
            payerMobile?: string;
            payerEmail?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UpdatePaymentDto: {
            /**
             * @example EXPENSE
             * @enum {string}
             */
            type?: "INCOME" | "EXPENSE";
            /**
             * @example FEED
             * @enum {string}
             */
            category?: "MILK_SALES" | "ANIMAL_SALES" | "FEED" | "MEDICINE" | "EQUIPMENT" | "LABOR" | "UTILITIES" | "MAINTENANCE" | "VETERINARY" | "TRANSPORT" | "INVESTMENT" | "OTHER_INCOME" | "OTHER_EXPENSE";
            /** @example 500 */
            amount?: number;
            /** @example Updated description */
            description?: string;
            /** @example 2026-03-10 */
            date?: string;
            /** @example 2026-03-10 */
            transactionDate?: string;
            /**
             * @example UPI
             * @enum {string}
             */
            paymentMethod?: "CASH" | "CARD" | "UPI" | "BANK_TRANSFER" | "CHEQUE";
            /** @example expense_123 */
            referenceId?: string;
            /**
             * @example EXPENSE
             * @enum {string}
             */
            referenceType?: "EXPENSE" | "DELIVERY" | "VET_VISIT" | "FEEDING_LOG" | "OTHER";
            /** @example Updated notes */
            notes?: string;
            /** @example false */
            isDeleted?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_seed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_root: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseDto"];
                };
            };
        };
    };
    AuthController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserDto"];
                };
            };
        };
    };
    UsersController_findAll: {
        parameters: {
            query: {
                farmId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnimalsController_findAll: {
        parameters: {
            query: {
                farmId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalDto"][];
                };
            };
        };
    };
    AnimalsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAnimalDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalDto"];
                };
            };
        };
    };
    AnimalsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalDto"];
                };
            };
        };
    };
    AnimalsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalDto"];
                };
            };
        };
    };
    AnimalsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnimalDto"];
                };
            };
        };
    };
    MilkRecordsController_findAll: {
        parameters: {
            query: {
                animalId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MilkRecordDto"][];
                };
            };
        };
    };
    MilkRecordsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMilkRecordDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MilkRecordDto"];
                };
            };
        };
    };
    MilkRecordsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MilkRecordDto"];
                };
            };
        };
    };
    MilkRecordsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MilkRecordDto"];
                };
            };
        };
    };
    MilkRecordsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MilkRecordDto"];
                };
            };
        };
    };
    WorkersController_findAll: {
        parameters: {
            query: {
                farmId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerDto"][];
                };
            };
        };
    };
    WorkersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerDto"];
                };
            };
        };
    };
    WorkersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerDto"];
                };
            };
        };
    };
    WorkersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerDto"];
                };
            };
        };
    };
    WorkersController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerDto"];
                };
            };
        };
    };
    TasksController_findAll: {
        parameters: {
            query: {
                farmId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDto"][];
                };
            };
        };
    };
    TasksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDto"];
                };
            };
        };
    };
    TasksController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDto"];
                };
            };
        };
    };
    TasksController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDto"];
                };
            };
        };
    };
    TasksController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDto"];
                };
            };
        };
    };
    FeedingController_findAll: {
        parameters: {
            query: {
                animalId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedingLogDto"][];
                };
            };
        };
    };
    FeedingController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFeedingLogDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedingLogDto"];
                };
            };
        };
    };
    FeedingController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedingLogDto"];
                };
            };
        };
    };
    FeedingController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedingLogDto"];
                };
            };
        };
    };
    FeedingController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFeedingLogDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedingLogDto"];
                };
            };
        };
    };
    DeliveriesController_findAll: {
        parameters: {
            query: {
                farmId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryDto"][];
                };
            };
        };
    };
    DeliveriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeliveryDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryDto"];
                };
            };
        };
    };
    DeliveriesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryDto"];
                };
            };
        };
    };
    DeliveriesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryDto"];
                };
            };
        };
    };
    DeliveriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeliveryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryDto"];
                };
            };
        };
    };
    VetController_findAll: {
        parameters: {
            query: {
                animalId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VetVisitDto"][];
                };
            };
        };
    };
    VetController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVetVisitDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VetVisitDto"];
                };
            };
        };
    };
    VetController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VetVisitDto"];
                };
            };
        };
    };
    VetController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VetVisitDto"];
                };
            };
        };
    };
    VetController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVetVisitDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VetVisitDto"];
                };
            };
        };
    };
    FarmDevelopmentController_getPhases: {
        parameters: {
            query: {
                farmId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmDevelopmentPhaseDto"][];
                };
            };
        };
    };
    FarmDevelopmentController_createPhase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePhaseDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmDevelopmentPhaseDto"];
                };
            };
        };
    };
    FarmDevelopmentController_getPhase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmDevelopmentPhaseDto"];
                };
            };
        };
    };
    FarmDevelopmentController_deletePhase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmDevelopmentPhaseDto"];
                };
            };
        };
    };
    FarmDevelopmentController_updatePhase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePhaseDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmDevelopmentPhaseDto"];
                };
            };
        };
    };
    FarmDevelopmentController_getMilestones: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                phaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmDevelopmentMilestoneDto"][];
                };
            };
        };
    };
    FarmDevelopmentController_createMilestone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                phaseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMilestoneDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmDevelopmentMilestoneDto"];
                };
            };
        };
    };
    FarmDevelopmentController_getMilestone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmDevelopmentMilestoneDto"];
                };
            };
        };
    };
    FarmDevelopmentController_deleteMilestone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmDevelopmentMilestoneDto"];
                };
            };
        };
    };
    FarmDevelopmentController_updateMilestone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMilestoneDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmDevelopmentMilestoneDto"];
                };
            };
        };
    };
    FarmDevelopmentController_completeMilestone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmDevelopmentMilestoneDto"];
                };
            };
        };
    };
    FarmDevelopmentController_getProgress: {
        parameters: {
            query: {
                farmId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_findAll: {
        parameters: {
            query: {
                farmId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentDto"][];
                };
            };
        };
    };
    PaymentsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePaymentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentDto"];
                };
            };
        };
    };
    PaymentsController_findIncome: {
        parameters: {
            query: {
                farmId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentDto"][];
                };
            };
        };
    };
    PaymentsController_findExpenses: {
        parameters: {
            query: {
                farmId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentDto"][];
                };
            };
        };
    };
    PaymentsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentDto"];
                };
            };
        };
    };
    PaymentsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentDto"];
                };
            };
        };
    };
    PaymentsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePaymentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentDto"];
                };
            };
        };
    };
    WalletController_getWallet: {
        parameters: {
            query: {
                farmId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WalletController_getWalletWithTransactions: {
        parameters: {
            query: {
                farmId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
