import createClient from 'openapi-fetch';

// The schema types are generated by `openapi-typescript` into `openapi/schema.d.ts`.
import type { paths } from '../openapi/schema.d.ts';

export type { paths };

export type ApiClient = ReturnType<typeof createClient<paths>>;

export function createApiClient(baseUrl: string) {
  return createClient<paths>({ baseUrl });
}
